# Generated by Django 4.2.19 on 2025-03-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPH', '0002_photomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockDoorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
